# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-14 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auth_group',
            options={'verbose_name': '\u6743\u9650\u7ec4\u7ba1\u7406', 'verbose_name_plural': '\u6743\u9650\u7ec4\u7ba1\u7406'},
        ),
        migrations.AlterField(
            model_name='auth_group',
            name='explanation',
            field=models.TextField(verbose_name='\u6743\u9650\u7ec4\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='auth_group',
            name='group_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='\u6743\u9650\u7ec4\u540d\u79f0'),
        ),
    ]
